app/forms/__init__.py
# flake8: noqa F401
from .email import EmailForm

app/forms/email.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField
from wtforms.validators import DataRequired


class EmailForm(FlaskForm):
    name = StringField("Name", [DataRequired()])
    email = EmailField("Email", [DataRequired()])
    submit = SubmitField("Login")

app/__init__.py
from dotenv import load_dotenv

from flask import Flask
from flask_mail import Mail


load_dotenv()


# app = Flask(__name__)


mail = Mail()


def create_app():
    from app.views import (
        email_blueprint,
        main_blueprint,
        home_blueprint,
    )

    app = Flask(__name__)

    app.config["SECRET_KEY"] = "3000a5aa-103e-4744-a12e-5333e0f672d9"

    app.config["MAIL_SERVER"] = "smtp.gmail.com"
    app.config["MAIL_PORT"] = 465
    app.config["MAIL_USERNAME"] = "andrii.berezianskii@gmail.com"
    app.config["MAIL_PASSWORD"] = "qkroxzhzlcilmkvw"
    app.config["MAIL_USE_TLS"] = False
    app.config["MAIL_USE_SSL"] = True

    mail.init_app(app)

    app.register_blueprint(email_blueprint)
    app.register_blueprint(main_blueprint)
    app.register_blueprint(home_blueprint)

    return app

app/views/__init__.py
# flake8: noqa F401
from .email import email_blueprint
from .main import main_blueprint
from .home import home_blueprint

app/views/email.py
from app import mail
from flask_mail import Message
from flask import Blueprint, render_template

email_blueprint = Blueprint("email", __name__)


@email_blueprint.route("/email")
def send_email():
    # msg = Message(
    #     "Hello",
    #     sender="andrii.berezyanskii@gmail.com",
    #     recipients=["andrey.berezyanskiy@gmail.com"],
    # )
    # msg.body = "Hello Flask message sent from Flask-Mail"
    # msg.html = render_template("email-layout.html")
    # mail.send(msg)

    return render_template("email-layout.html", name="Andrii")

app/views/home.py
from flask import Blueprint, render_template

home_blueprint = Blueprint("home", __name__)


@home_blueprint.route("/home")
def home():
    return "h"

app/views/main.py
from flask import Blueprint, render_template
from app import mail
from flask_mail import Message
from app.forms import EmailForm


main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/main", methods=["GET", "POST"])
def main():
    form = EmailForm()

    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()

        if name and email:
            msg = Message(
                "Hello",
                sender="andrii.berezyanskii@gmail.com",
                recipients=[f"{email}"],
            )
            # msg.body = "Hello Flask message sent from Flask-Mail"
            msg.html = render_template("email-layout.html", name=name)
            mail.send(msg)
            return render_template("success.html")

    return render_template("home.html", form=form)

app/templates/email-layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    table, td, div, h1, p {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    h1, h2, h3, h4 {
      color: #154734;
    }
    
    .btn:hover {
      box-shadow: 0px 0px 1px 1px #3f4c43;
    }

    a {
      text-decoration: none;
      color: #154734;
    }

    @media screen and (max-width: 500px){
      .col-lg {
      display: block;
      width: 100% !important;
      text-align: center;
    }
    .main-image {
      width: 100% !important;
      max-width: 100% !important;
      height: auto !important;
    }
    }
  </style>
</head>
<body style="margin:0; padding:0;word-spacing:normal;">
  <div role="article" aria-roledescription="email" lang="en" style="text-size-adjust:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">
    <table role="presentation" style="width:100%;border:none;border-spacing:0;">
      <tr>
        <td align="center" style="padding:0;">
          <table role="presentation" style="width:94%; max-width:600px; border: none; border-spacing: 0; color: #333; text-align: left; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 20px;line-height: 24px;">
            <!-- <tr>
              <td>
                <a href="http://google.com/" style="text-decoration: none;">
                  <img src="{{ url_for('static', filename='img/logo.svg', _external=True) }}" alt="Logo">
                </a>
              </td>
            </tr> -->
            <tr>
              <td style="padding: 30px 30px 15px; background-color: #a4c5b4; background-image: url({{ url_for('static', filename='img/background.png') }});">
                <h1 style="margin-bottom: 50px; font-size: 50px; line-height: 62px; font-weight: bold; ">
                  Welcome to UGS, <br> {{ name }}!
                </h1>
                <p>
                  We are University Graphic Systems, a student-run and operated print service located on Cal Poly’s campus.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding: 20px;">
                <h3 style="margin-bottom: 30px; font-size: 35px; font-weight: bold;">
                  About Our Shop
                </h3>
                <p>
                  UGS offers a number of template designs, t-shirts, and stickers! All of these products are available in our storefront, email us at <span style="text-decoration: none; font-weight: bold; color: #154734;">ugs@calpoly.edu</span> about availability of these products or if you have any questions.
                </p>
              </td>
            </tr>
            <tr>
              <td>
                <table role="presentation" width="100%" style="table-layout: fixed; border-spacing: 20px;">
                  <tr>
                      <td class="col-lg">
                        <img class="main-image" style=" width: 100%; height: auto;" src="{{ url_for('static', filename='img/img1.png', _external=True) }}" alt="">
                      </td>
                      <td class="col-lg" style=" text-align: left; vertical-align: top;">
                          <h3>
                            Resume
                          </h3>
                          <p>
                            Eight unique resume templates available. Templates cost $15 plus the cost of printing, see our services page for pricing.
                          </p>
                      </td>
                  </tr>
                  <tr>
                      <td class="col-lg" style="text-align: right; vertical-align: top;">
                        <h3>
                          Business Cards
                        </h3>
                        <p>
                          Eight unique templates available. Templates cost $15 plus the cost of printing, see our services page for pricing.
                        </p>
                      </td>
                      <td class="col-lg">
                        <img class="main-image" style="width: 100%; height: auto; margin-bottom: 20px;" src="{{ url_for('static', filename='img/img2.png', _external=True) }}" alt="">
                      </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td style="text-align: center;">
                <a class="btn" href="https://facebokk.com" style="display:inline-block; margin-bottom: 30px; padding: 10px 20px; text-decoration: none; background-color: #305e4c; color: #fff; padding: 20px;"> View Our Shop</a>
              </td>
            </tr>
            <tr>
              <td style="padding: 30px 100px 5px; text-align: center; font-size: 15px; background-color: #e5e5e5;">
                <div>
                  <img src="{{ url_for('static', filename='img/logo-i.png', _external=True) }}" alt="">
                  <img src="{{ url_for('static', filename='img/logof.png', _external=True) }}" alt="">
                  <img src="{{ url_for('static', filename='img/logo-l.png', _external=True) }}" alt="">
                </div>
                <p style="margin-bottom: 20px;"> www.ugs.com <br> 8050809</p>
                <p>Building 26, Room 212A <br> San Luis, CA 93405</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body style="height: 100vh; overflow: hidden; display: flex; justify-content: center; align-items: center; background-color: #87928b;">
    <div style=" background-color: #3e4848; ">
      <form role="form"  action="{{ url_for('main.main') }}" method="post" style="padding: 48px; display: flex; height: 100%; flex-direction: column; justify-content: start;">
        {{ form.csrf_token }}
        <div style="margin-bottom: 24px;">
          {{form.name(style="padding: 5px; background-color: #d7d7d7", placeholder="Input Your Name")}}
        </div>
        <div style="margin-bottom: 24px;"style="margin-bottom: 24px;">
          {{form.email(style="padding: 5px; background-color: #d7d7d7",  placeholder="Input Your Email") }}
        </div>
        <button style=" display: inline-block; padding: 20px; justify-self: flex-end; background-color: #d7d7d7; cursor: pointer;" type="submit" class="">
            <span class="">Send Email</span>
        </button>
      </form>
    </div>
</body>
</html>

app/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body style="height: 100vh; overflow: hidden;  background-color: #87928b;">
  <h2 style="text-align: center;">Email was sent</h2>
</body>
</html>